version: "3"
services:
    web:
        ports:
            - 8080:80
    server:
        ports:
            - 9230:9230
            - 3333:3333
        environment:
            - DEV=true
    db:
        ports:
            - 5432:5432
