version: "3"
volumes:
    db_data:
services:
    web:
        image: nginx:alpine
        restart: always
        volumes:
            - ./nginx.conf:/etc/nginx/conf.d/default.conf
            - ../html:/www
            - ./data/logs:/logs
        links:
            - server
        networks:
            - network

    server:
        build:
            context: .
            dockerfile: Dockerfile
        environment:
            PORT: 3333
            DATABASE: ${CHITTER_DB}
            DATABASE_USER: ${CHITTER_DB_USER}
            DATABASE_PASSWORD: ${CHITTER_DB_PASSWORD}
            SHUTDOWN_TOKEN: ${CHITTER_SHUTDOWN_TOKEN}
        volumes:
            - ./data:/data
            - ../:/app
        links:
            - db
        networks:
            - network
    db:
        build:
            context: .
            dockerfile: Dockerfile.postgres
        restart: always
        environment:
            POSTGRES_DB: ${CHITTER_DB}
            POSTGRES_USER: ${CHITTER_DB_USER}
            POSTGRES_PASSWORD: ${CHITTER_DB_PASSWORD}
        volumes:
            - db_data:/var/lib/postgresql/data
        networks:
            - network

networks:
    network:
        driver: bridge
